### ISSUE TITLE
Expressão regular para validar endereço de e-mail

### ISSUE THREAD

**Issue by EmanuelJoseCandido** [martygo/regex.ao#1]
Olá **@martygo** , seria interessante se na tua colecção de expressões regulares também tivesse,  algum tipo de _expressão regular para validar endereço de e-mail_.

Existem vários, escolherias e testarias, um que se adapte melhor ao teu repositório.

**Comment by martygo** [comment]
Valeu pela sugestão.

**Comment by martygo** [comment]
*Olá @EmanuelJoseCandido, adicionei uma regex simples para verificação de email. Agradeceria se desse uma testada  e me retornasse um feedback*.

**Comment by EmanuelJoseCandido** [comment]
Olá, @martygo, testei o regex adicionado para validar o email, está a funcionar perfeitamente, apenas esqueceste a barra invertida no início e no fim do regex.
